name: CI

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build-linux-x8664:
    name: Linux x86_64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - name: Checkout ksw2
      uses: actions/checkout@v4

    - name: Compile with ${{ matrix.compiler }}
      run: |
        make CC=${{ matrix.compiler }}
        file ksw2-test | grep x86-64

  build-linux-aarch64:
    name: Linux aarch64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc]

    steps:
    - name: Checkout ksw2
      uses: actions/checkout@v4

    - name: Compile with ${{ matrix.compiler }}
      uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: ubuntu22.04
        githubToken: ${{ github.token }}
        dockerRunArgs: |
          --volume "${PWD}:/ksw2"
        install: |
          apt-get update -q -y
          apt-get install -q -y make ${{ matrix.compiler }} zlib1g-dev file
        run: |
          cd /ksw2
          make CC=${{ matrix.compiler }} arm_neon=1 aarch64=1 -j
          file ksw2-test | grep aarch64

  build-mac-arm64:
    name: Mac ARM64
    runs-on: macos-14
    strategy:
      matrix:
        compiler: [clang]

    steps:
    - name: Checkout ksw2
      uses: actions/checkout@v4

    - name: Compile with ${{ matrix.compiler }}
      run: |
        make CC=${{ matrix.compiler }} arm_neon=1 aarch64=1 -j
        file ksw2-test | grep arm64
        
